plugins {
  id "org.sonarqube" version "6.2.0.5505"
}

sonar {
  properties {
    property "sonar.projectKey", "sample-websitescan"
    property "sonar.projectName", "sample-websitescan"
  }
}
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "merchant_sdk"
include ':app'
include ':merchantsdk'
